site_name: Seminar Aktuelle Themen der künstlichen Intelligenz
nav:
- Aktuelles: index.md
- ...
- Impressum: impressum.md

theme:
  name: material
  features:
    - navigation.expand
    - navigation.indexes

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - footnotes

plugins:
  - search
  - awesome-pages:
      collapse_single_pages: false

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

